name: Deploy Backend to VPS NAT

on:
  push:
    branches: [main] # Chạy khi bạn push vào branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Thiết lập Docker buildx để hỗ trợ cache
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker layers để giảm thời gian build
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{runner.os}}-buildx-${{github.sha}}
          restore-keys: |
            ${{runner.os}}-buildx-
      
      # Build image và lưu vào bộ nhớ đệm (ko đẩy lên Register)
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          outputs: type=docker,dest=/tmp/my-image.tar
          tags: backend-app:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Di chuyển vào thư mục dự án
            cd /home/tutorial-nodejs-ci || exit

            # Kéo code mới về
            git pull origin main

            # 3. Build lại image mới và khởi động lại container bằng docker compose
            sudo docker-compose up -d --build
            
            # 6. Dọn dẹp các image cũ không dùng để tiết kiệm ổ cứng VPS
            sudo docker image prune -f
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
