name: Deploy Backend to VPS NAT

on:
  push:
    branches: [ main ] # Chạy khi bạn push vào branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Di chuyển vào thư mục dự án
            cd /home/tutorial-nodejs-ci || exit
            
            # Kéo code mới về
            git pull origin main

            # 3. Build lại image mới
            sudo docker build -t backend-app .

            # 4. Dừng và xóa container cũ nếu đang chạy
            sudo docker stop backend || true
            sudo docker rm backend || true

            # 5. Chạy container mới với port 5000
            docker run -d \
              --name backend-container \
              --restart always \
              -p 5000:5000
              backend-app
            # 6. Dọn dẹp các image cũ không dùng để tiết kiệm ổ cứng VPS
            docker image prune -f 

